import { Waves, Info } from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";


export function AppHeader() {
  return (
    <header className="py-8 text-center">
      <div className="inline-flex items-center gap-3">
        <Waves className="h-12 w-12 text-primary" />
        <h1 className="text-5xl font-bold tracking-tight">
          <span className="bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">
            Quantum Leap
          </span>
        </h1>
      </div>
      <p className="mt-2 text-lg text-muted-foreground">
        AI-Powered Crypto Insights for Quick Profits
      </p>
      <Alert variant="default" className="mt-6 max-w-2xl mx-auto text-sm bg-card/30 border-primary/30 text-left">
        <Info className="h-5 w-5 text-primary" />
        <AlertTitle className="text-primary/90">Important Disclaimer</AlertTitle>
        <AlertDescription className="text-muted-foreground">
          The information provided by Quantum Leap is generated by an AI and is for informational purposes only. It should not be considered financial advice. Cryptocurrency investments are highly volatile and carry significant risk. Past performance is not indicative of future results. Always do your own research (DYOR) and consult with a qualified financial advisor before making any investment decisions. We cannot guarantee the accuracy or completeness of the AI's predictions.
        </AlertDescription>
      </Alert>
    </header>
  );
}
